name: Static analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - name: Install dependencies
          run: |
            python -m pip install flake8
        - name: Run flake8
          run: |
            # ignore errors for long lines and multi-statement lines
            python -m flake8 --ignore=E501,E701,W503 speech_recognition tests examples setup.py

        - name: Convert JUnit XML to HTML
          run: |
            junit2html flake8_report.xml flake8_report.html

        - name: Upload Flake8 HTML report
          uses: actions/upload-artifact@v3
          with:
            name: flake8-html-report
            path: flake8_report.html
